### ISSUE TITLE
Not working in Ubuntu

### ISSUE THREAD

**Issue by fabriciolelis** [codealchemist/hyper-transparent#3]
I've installed hyper terminal and put your plugin but hyper says than it is not possible load the plugin.

**Comment by mike3run** [comment]
vibrancy is a mac thing?

**Comment by codealchemist** [comment]
Hi @fabriciolelis!
Today I rolled out a new version of **HyperTransparent** and there are new versions of **Hyper** as well. Is this still happening? Thx!

@mike3run yup!
From the official docs:
> vibrancy String (optional) - Add a type of vibrancy effect to the window, only on macOS.
https://electronjs.org/docs/api/browser-window

**Comment by NerdsvilleCEO** [comment]
Happens for me on Xubuntu 18.04 LTS

**Comment by Alfian5229** [comment]
linux manjaro is not working too

**Comment by codealchemist** [comment]
Hi guys!
After some investigation, particularly:
https://stackoverflow.com/questions/54763647/transparent-windows-on-linux-electron

I tried this:
https://gitlab.com/doom-fr/electron-transparency-demo

And I was able to make transparency work on Ubuntu.
The problem is...
Hyper needs to be built using `--enable-transparent-visuals --disable-gpu` and...
We need to wait some ms before creating the Electron window object, which is not supported by Hyper and needs some hacking of its source code.

Maybe we can create a PR against Hyper to allow plugins to affect how the window object is created... Still, we'll need to pass those params which I believe only work at build time.
And the problem is not on Hyper or Electron itself.

It looks like this goes back to:
![image](https://user-images.githubusercontent.com/1118293/78747945-20e5fd00-7941-11ea-81e6-7fefb86d5b33.png)

If someone has other ideas we can explore them.
Regarding _"vibrancy"_ we can look for a way to hide the option on platforms other than OSX, since it's only supported there.

Thanks!

**Comment by lajennylove** [comment]
Is hyperTransparent working on Mac M1? Because I've an Intel MacBook and it worked perfect, but I set the same settings on my new Mac M1 and it just doesn't work. That's why I came here just to know if there's some known issue or is just me that I made something wrong.

![Screen Shot 2022-01-29 at 12 54 16 AM](https://user-images.githubusercontent.com/5205775/151649446-2eb4c6ec-2a13-4b93-87c0-8cc480488b3e.png)

![Screen Shot 2022-01-29 at 12 55 43 AM](https://user-images.githubusercontent.com/5205775/151649493-f63b2cd0-46b9-4a27-bb7b-8b3e6d30d91f.png)


Thanks!

**Comment by codealchemist** [comment]
Hi @lajennylove !
Sadly I don't have a MacBook M1 to test it.
If I can get my hands on one I'll try to reproduce and see if we can find a fix for it.
Sorry!

**Comment by lajennylove** [comment]
> Hi @lajennylove !
> Sadly I don't have a MacBook M1 to test it.
> If I can get my hands on one I'll try to reproduce and see if we can find a fix for it.
> Sorry!

Hy @codealchemist, I finally make it work, I don't know what it was but I just copied my MacBook's .backup_hyper.js and my .hyper_plugins into my M1 Mac mini and it worked. I've not idea what was happened but, tested it works perfectly on M1 processors. 

Best Regards!

**Comment by ritog** [comment]
> vibrancy is a mac thing?
~ @shelldandy 

Vibrancy worked for me in Linux successfully only in Kubuntu. Haven't worked for me in any other way. Note that I am talking about the Konsole application only.
